// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TravelDeskProject.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    [Migration("20240219134742_tables-added")]
    partial class tablesadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AadharNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("BookingTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("From")
                        .HasColumnType("int");

                    b.Property<int?>("HotelLocationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("MealPreferenceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MealTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForTravelling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StayDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("To")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TravelDeskProject.Models.BookingType", b =>
                {
                    b.Property<int>("BookingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingTypeId"));

                    b.Property<string>("BookingTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingTypeId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingTypeId = 1,
                            BookingTypeName = "Air ticket Only",
                            CreateBy = 0,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            BookingTypeId = 2,
                            BookingTypeName = "Hotel Only",
                            CreateBy = 0,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        },
                        new
                        {
                            BookingTypeId = 3,
                            BookingTypeName = "Both",
                            CreateBy = 0,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4221),
                            DepartmentName = "IT",
                            IsActive = false
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4222),
                            DepartmentName = "Sales",
                            IsActive = false
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4223),
                            DepartmentName = "HR",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.FlightType", b =>
                {
                    b.Property<int>("FlightTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightTypeId"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("FlightTypeId");

                    b.ToTable("FlightTypes");

                    b.HasData(
                        new
                        {
                            FlightTypeId = 1,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4163),
                            FlightTypeName = "Domestic",
                            IsActive = false
                        },
                        new
                        {
                            FlightTypeId = 2,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4166),
                            FlightTypeName = "International",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            City = "Noida",
                            Country = "India",
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4201),
                            IsActive = false
                        },
                        new
                        {
                            LocationId = 2,
                            City = "Pune",
                            Country = "India",
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4202),
                            IsActive = false
                        },
                        new
                        {
                            LocationId = 3,
                            City = "London",
                            Country = "England",
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4204),
                            IsActive = false
                        },
                        new
                        {
                            LocationId = 4,
                            City = "Dubai",
                            Country = "United Arab Emirates",
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4205),
                            IsActive = false
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.MealPreferenceType", b =>
                {
                    b.Property<int>("MealPreferenceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealPreferenceTypeId"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MealPreferenceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("MealPreferenceTypeId");

                    b.ToTable("MealPreferenceTypes");

                    b.HasData(
                        new
                        {
                            MealPreferenceTypeId = 1,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4099),
                            IsActive = false,
                            MealPreferenceName = "Veg"
                        },
                        new
                        {
                            MealPreferenceTypeId = 2,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4102),
                            IsActive = false,
                            MealPreferenceName = "Non-Veg"
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.MealType", b =>
                {
                    b.Property<int>("MealTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealTypeId"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MealTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("MealTypeId");

                    b.ToTable("MealTypes");

                    b.HasData(
                        new
                        {
                            MealTypeId = 1,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4120),
                            IsActive = false,
                            MealTypeName = "Lunch"
                        },
                        new
                        {
                            MealTypeId = 2,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4122),
                            IsActive = false,
                            MealTypeName = "Dinner"
                        },
                        new
                        {
                            MealTypeId = 3,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4123),
                            IsActive = false,
                            MealTypeName = "Both"
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(3965),
                            IsActive = false,
                            ProjectName = "GBS-UK"
                        },
                        new
                        {
                            ProjectId = 2,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(3977),
                            IsActive = false,
                            ProjectName = "GBS-Dubai"
                        },
                        new
                        {
                            ProjectId = 3,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(3978),
                            IsActive = false,
                            ProjectName = "GBS-Noida"
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4239),
                            IsActive = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4240),
                            IsActive = false,
                            RoleName = "HRAdmin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4242),
                            IsActive = false,
                            RoleName = "Employee"
                        },
                        new
                        {
                            RoleId = 4,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4242),
                            IsActive = false,
                            RoleName = "Manager"
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StatusId");

                    b.ToTable("EmployeeRequestStatus");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4183),
                            IsActive = false,
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4185),
                            IsActive = false,
                            StatusName = "Rejected"
                        },
                        new
                        {
                            StatusId = 3,
                            CreateBy = 0,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4186),
                            IsActive = false,
                            StatusName = "Approved"
                        });
                });

            modelBuilder.Entity("TravelDeskProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Mzp",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4265),
                            DepartmentId = 1,
                            Email = "priya@gmail.com",
                            FirstName = "Priya",
                            IsActive = true,
                            LastName = "Jaiswal",
                            MobileNumber = "6306788371",
                            Password = "Priya@123",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Delhi",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2024, 2, 19, 19, 17, 42, 175, DateTimeKind.Local).AddTicks(4269),
                            DepartmentId = 2,
                            Email = "erica@gmail.com",
                            FirstName = "Erica",
                            IsActive = true,
                            LastName = "Attal",
                            ManagerId = 1,
                            MobileNumber = "9090909090",
                            Password = "Erica@123",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Request", b =>
                {
                    b.HasOne("TravelDeskProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelDeskProject.Models.User", b =>
                {
                    b.HasOne("TravelDeskProject.Models.Department", "Department")
                        .WithMany("User")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelDeskProject.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("TravelDeskProject.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TravelDeskProject.Models.Department", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelDeskProject.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
